### ISSUE TITLE
Cannot update versionName if it's a variable

### ISSUE THREAD

**Issue by tsengvn** [bitrise-steplib/steps-change-android-versioncode-and-versionname#11]
In my project, I used the gradle like this 
```
defaultConfig {
        minSdkVersion min_sdk_version
        targetSdkVersion target_sdk_version
        versionCode version_code
        versionName version_name
        multiDexEnabled true
        applicationId "com.app.test"

    }
```
The plugin is failed to find and replace the versionName because you are looking for a string value that starts and ends with " (or ')

Why we don't just find the line begins with "versionName" then replace the full line with`versionName (our value)` instead of finding the value inside the quotes (or double quotes)

**Comment by BirmacherAkos** [comment]
Hi!

Thanks for the issue report. I have created a ticket, and the Tooling Team will check it.

**Comment by ayoubkhayatti** [comment]
Is there anything new about this? I'm facing the same issue.

**Comment by BirmacherAkos** [comment]
Hi!

The Tooling Team has a ticket for this issue but it's not solved yet.
Sorry for the inconvenience.

**Comment by Diego-Franco** [comment]
This issue will be fixed soon?

**Comment by tsengvn** [comment]
hi @Diego-Franco we created a script to update by our own

**Comment by Diego-Franco** [comment]
@tsengvn can you share how you make that script? or you just replace whatever is on the value?

**Comment by ayoubkhayatti** [comment]
@Diego-Franco `sed -i -e 's/versionName version/versionName "'$VERSION_NAME'"/g' ./scripts/app.gradle;`

I'm replacing the whole line `versionName version` with an env variable. Note that my version name is in a different file than build.gradle. please replace the path to your project specifics.

**Comment by condesales** [comment]
I know it's not ideal but you can do something like
```groovy
defaultConfig {
    minSdkVersion min_sdk_version
    targetSdkVersion target_sdk_version
    versionCode version_code
    versionName "$version_name"
    multiDexEnabled true
    applicationId "com.app.test"
 }
```   
at that should work

**Comment by duanniston** [comment]
I Have the same issue

**Comment by trapacska** [comment]
Hey @duanniston, @condesales, @ayoubkhayatti, @tsengvn, @Diego-Franco!

This release should fix this problem, please check and let us know if it is fixed: https://github.com/bitrise-steplib/steps-change-android-versioncode-and-versionname/releases/tag/1.2.0

🚀

**Comment by jlo1** [comment]
@trapacska -- thanks for addressing!
Couple things I noticed:

1. It will not properly copy over versionName as a string. Will update as follows
```
versionName rootProject.ext.versionName ->         versionName 5.28.0
```
but we actually want to update such that it's `versionName "5.28.0"`.
(Note: `rootProject.ext.versionName` is defined as `"5.28.0"`)


2. It will improperly update some variables.
```
versionCodes.get(abi) * 1048576 + defaultConfig.versionCode ->                         versionCode16504 * 1048576 + defaultConfig.versionCode
```
But we actually want to retrieve the value from a variable we have defined above
`def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a": 3, "x86_64": 4]`

**Comment by jlo1** [comment]
@trapacska -- thanks for addressing!
Couple things I noticed:

---
1. It **will** properly update versionCode now
```
versionCode rootProject.ext.versionCode ->   versionCode 555
```

---
2. It **will not properly copy over versionName as a string**. Will update as follows
```
versionName rootProject.ext.versionName ->   versionName 1.1.0
```
but we actually want to update such that it's `versionName "1.1.0"`.
(Note: `rootProject.ext.versionName` is defined as `"1.1.0"`)

---
3. It **will improperly update some variables**.
```
versionCodes.get(abi) * 1000 + defaultConfig.versionCode ->                         versionCode555 * 1000 + defaultConfig.versionCode
```
But we actually want to retrieve the value from a variable we have defined above
`def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a": 3, "x86_64": 4]`

**Comment by godrei** [comment]
Hi @jlo1 and @tsengvn ,

we fixed the issue ([see the new test cases](https://github.com/bitrise-steplib/steps-change-android-versioncode-and-versionname/releases/tag/1.2.4)) in version [1.2.4](https://github.com/bitrise-steplib/steps-change-android-versioncode-and-versionname/releases/tag/1.2.4), the new version will be available in the StepLib in ~20m.

Thanks for the detailed report and the contribution to everyone!

I'll close this issue, but if you need more info/help just let us know by opening a new one!
