### ISSUE TITLE
Erro building Android

### ISSUE THREAD

**Issue by AdeilsonSuperlogica** [bitrise-steplib/steps-change-android-versioncode-and-versionname#20]
Hi,
When compiling the Android application using the latest version I am getting the following error:
`groovy.lang.MissingPropertyException: Could not get unknown property 'versionCode14841' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.`

When using version 1.1.1 this error does not occur.

**Comment by jamesjara** [comment]
same

**Comment by jamesjara** [comment]
Solved.

```    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride = versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
```

The step is replacing the default value `versionCodeOverride` to `versionCode<ID>` so the gradle compilation fails

**Comment by zoran888** [comment]
It is occurring sometimes. 
I used gradle-runner step before and I encountered above issue so changed to Android build step and worked fine for two builds. But now I am encountering this issue again.

Really difficult to use

**Comment by chaitanyatanna-bitrise** [comment]
Hello @zoran888 
Can you please send us the build URL with the enabled Support user?

Thanks
Chaitanya
