### ISSUE TITLE
versionCode regex not specific enough

### ISSUE THREAD

**Issue by PhilippeCollin** [bitrise-steplib/steps-change-android-versioncode-and-versionname#21]
The version code regex seems not specific enough at the moment and I think this might cause problems for a lot of react native projects with standard setups.

The step will modify completely unrelated code like the following:
```
def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
versionCodes.get(abi) * 1000 + defaultConfig.versionCode
```
With a build number of 50, the second line gets replaced by :
```
versionCode50 * 1000 + defaultConfig.versionCode
```
This piece of code is from a standard react native setup using `npx react-native init`.

_As reported by @jlo1 in https://github.com/bitrise-steplib/steps-change-android-versioncode-and-versionname/issues/11#issuecomment-555297817_

**Comment by arjun-livquik** [comment]
I am facing this issue too

```
Updating versionName and versionCode in: /Users/vagrant/git/android/app/build.gradle
updating line (109):         versionCode 9 ->         versionCode 228
updating line (178):                         versionCodes.get(abi) * 1048576 + defaultConfig.versionCode ->                         versionCode228 * 1048576 + defaultConfig.versionCode
```

**Comment by fabiendem** [comment]
Had the same issue,
Trick is to rename `versionCodes` to something different, mainly `version` with a capital `V` so the regex does not match it.

I did:
```
def architectureVersionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
architectureVersionCodes.get(abi) * 1000 + defaultConfig.versionCode
```

**Comment by josinaldobarbosa** [comment]
can someone help with the pr?

**Comment by godrei** [comment]
Hi @PhilippeCollin ,

we fixed the issue ([see the new test cases](https://github.com/bitrise-steplib/steps-change-android-versioncode-and-versionname/releases/tag/1.2.4)) in version [1.2.4](https://github.com/bitrise-steplib/steps-change-android-versioncode-and-versionname/releases/tag/1.2.4), the new version will be available in the StepLib in ~20m.

Thanks for the detailed report and the contribution to everyone!

I'll close this issue, but if you need more info/help just let us know by opening a new one!
