### ISSUE TITLE
Support multiple build.gradle files

### ISSUE THREAD

**Issue by tir38** [bitrise-steplib/steps-change-android-versioncode-and-versionname#22]
We are now using Dynamic Feature Modules which means that version code and version name in those modules has to match value in base app/build.gradle. So it would be nice if this step could set all of them at once.  I don't believe this will work at the moment (yes I know we can just copy this step but that seems tedious)

<img width="842" alt="Screen Shot 2020-03-17 at 2 44 19 PM" src="https://user-images.githubusercontent.com/1980553/76890524-e4e9db80-685d-11ea-83f7-6997e393cf75.png">

**Comment by bitce** [comment]
Thanks for the feature request @tir38! We've forwarded it to the relevant teams :)
