### ISSUE TITLE
versionName replace doesn't fully replace previous value

### ISSUE THREAD

**Issue by avi-mastov** [bitrise-steplib/steps-change-android-versioncode-and-versionname#23]
I have in my gradle file:

`versionName localProperties.getProperty('flutter.versionName')`
It gets replaced to:
`versionName XXX'flutter.versionName')`
where XXX is the input.

Also if I happen to store the value in a local var, such as:
```
        def versionCode = localProperties.getProperty('flutter.versionCode').toInteger()
        def versionName = localProperties.getProperty('flutter.versionName')
        versionCode versionCode
        versionName versionName
```
Then each of versionCode and versionName is duplicated...

**Comment by non-binary** [comment]
HI @avi-mastov,

Can you please send a link to a build that reproduces this?

**Comment by avi-mastov** [comment]
@non-binary this reproduces the first case:
https://app.bitrise.io/build/74f8d62f8ff2312f#?tab=log

**Comment by bitce** [comment]
Hi @avi-mastov!

Sorry for the delay. From the looks of it you sorted out the 2nd issue referenced here, is the first one still occurring?

**Comment by avi-mastov** [comment]
@bitce thanks for replying.

I worked around both issues by changing my code like this:

```
        def storedVersionCode = localProperties.getProperty('flutter.versionCode').toInteger()
        def storedVersionName = localProperties.getProperty('flutter.versionName')
        versionCode storedVersionCode
        versionName storedVersionName
```

I guess your code assumes that the rvalue is a literal and does some regex to identify and replace it. I would instead replace the entire line with a new statement.
