### ISSUE TITLE
Error when using variables from gradle with 1.2.4

### ISSUE THREAD

**Issue by spiritax** [bitrise-steplib/steps-change-android-versioncode-and-versionname#33]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.2.4
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Issue description

Before the last version, we were using this as variable :
inputs:
        - build_gradle_path: "$PROJECT_LOCATION/app/build.gradle"
        - new_version_name: project.ext.versionName + $BITRISE_BUILD_NUMBER

That was generating this : **1.6.0.11494**

with the latest version(1.2.4), we get this instead : **project.ext.versionName + 11492**

### Steps to reproduce

1. setup a project with a variable as versionName
2. use it in the change version name in the **Change Android versionCode and versionName** step
3. Look the resulting versionName

**Comment by Roland-Bak** [comment]
Hello @spiritax 👋

Can you please send us the log file or the URL of the related build and also enable Support Access on the Settings tab of the app ( https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/ ) so that we can take a more in-depth look? 🙂
