### ISSUE TITLE
Error taking variables from gradle in Change Android versionCode and versionName v1.2.4

### ISSUE THREAD

**Issue by Juan-GS** [bitrise-steplib/steps-change-android-versioncode-and-versionname#34]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.2.x
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time?  EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NO

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

We have a strange behavior in this workflow after updating to 1.2.x

#### Version Name and Version Code configuration in gradle file:

versionCode = versionMajor * 10000 + versionMinor * 100 + versionPatch
versionName = "$versionMajor.$versionMinor.$versionPatch"  

In Bitrise, we have set the version code as: $BITRISE_BUILD_NUMBER

Then, when this step is executed we can see the following output data:

### v1.0:
Configs:
- BuildGradlePth: XXX/app/build.gradle.kts
- NewVersionName: 
- NewVersionCode: 2799
- VersionCodeOffset: 
Updating versionName and versionCode in: XXX/app/build.gradle.kts
updating line (20):  
versionCode = DefaultConfig.versionMajor * 10000 + DefaultConfig.versionMinor * 100 +DefaultConfig.versionPatch  
->  versionCode 2799

### v1.1:
Configs:
- BuildGradlePth: XXX/app/build.gradle.kts
- NewVersionName: 
- NewVersionCode: 2803
- VersionCodeOffset: 
Updating versionName and versionCode in: XXX/app/build.gradle.kts
updating line (20):versionCode = 
DefaultConfig.versionMajor * 10000 + DefaultConfig.versionMinor*100+DefaultConfig.versionPatch  
->   versionCode 2803

#### 1- If we use the same configuration, that is, Gradle DSL using extensions, the step does not find the versionCode:

version: 1.2.4                                                               
collection: https://github.com/bitrise-io/bitrise-steplib.git                
toolkit: go                                                                  
 time: 2021-06-03T16:00:59Z                                                   

Config:
- BuildGradlePth: XXX/app/build.gradle.kts
- NewVersionName: 
- NewVersionCode: 2805
- VersionCodeOffset: 0
Updating versionName and versionCode in: XXX/app/build.gradle.kts
0 versionCode updated
0 versionName updated

#### 2- If we set the versionCode and versionName in app gradle.kts file, then we got the following:
BuildGradlePth: XXX/app/build.gradle.kts
- NewVersionName: 
- NewVersionCode: **2806**
- VersionCodeOffset: 0
Updating versionName and versionCode in: XXX/app/build.gradle.kts
updating line (20):         versionCode = 
DefaultConfig.versionMajor * 10000 + DefaultConfig.versionMinor * 100 + DefaultConfig.versionPatch 
->  versionCode = **2806** * 10000 + DefaultConfig.versionMinor * 100 + DefaultConfig.versionPatch
1 versionCode updated
0 versionName updated

Then, if we have, for example: version minor= 7 and versionPatch= 3, the version code is 280060703. This is a big problem if you use Google Play workflow due to your next apk will have 280060703 as the serial number and you can not upload an apk later less than this number...

It seems that Bitrise is taking the build number and replace the first variable in version code. There are other test that I have tried with a strange behavior:

#### 2.a - Using another variable before DefaultConfig.versionMajor

gradle:
val testBitrise = 0
applicationId = DefaultConfig.applicationId
versionName = "${DefaultConfig.versionMajor}.${DefaultConfig.versionMinor}.${DefaultConfig.versionPatch}"
versionCode = testBitrise + DefaultConfig.versionMajor * 10000 + DefaultConfig.versionMinor * 100 + DefaultConfig.versionPatch

BitRise output:
Config:
- BuildGradlePth: XXX/app/build.gradle.kts
- NewVersionName: 
- NewVersionCode: 2807
- VersionCodeOffset: 0
Updating versionName and versionCode in: XXX/app/build.gradle.kts

updating line (21):  versionCode =
 testBitrise + DefaultConfig.versionMajor * 10000 + DefaultConfig.versionMinor * 100 + DefaultConfig.versionPatch
 ->versionCode = 2807 + DefaultConfig.versionMajor * 10000 + DefaultConfig.versionMinor * 100+DefaultConfig.versionPatch
1 versionCode updated
0 versionName updated

#### 2.b: Renamed **versionMajor** to **v**
gradle:
 applicationId = DefaultConfig.applicationId
 versionName = "${DefaultConfig.v}.${DefaultConfig.versionMinor}.${DefaultConfig.versionPatch}"
  versionCode = DefaultConfig.v * 10000 + DefaultConfig.versionMinor * 100 + DefaultConfig.versionPatch

Bitrise output:
Config:
- BuildGradlePth: XXX/app/build.gradle.kts
- NewVersionName: 
- NewVersionCode: 2809
- VersionCodeOffset: 0
Updating versionName and versionCode in: XXX/app/build.gradle.kts
updating line (20):         versionCode = 
DefaultConfig.v * 10000 + DefaultConfig.versionMinor * 100 + DefaultConfig.versionPatch 
->   versionCode = `2809` * 10000 + `2809`ersionMinor * 100 + `2809`ersionPatch
1 versionCode updated
0 versionName updated

### Bitrise info

- Build URL: https://app.bitrise.io/build/42661781d014ee9d#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES 
- Log: 
I pasted the relevant log in Issue description trying to clarify how to reproduce this issue and the configuration. Please, let me know if you need more information.

### Steps to reproduce

1. Use 
versionName = "${DefaultConfig.versionMajor}.${DefaultConfig.versionMinor}.${DefaultConfig.versionPatch}"
versionCode = DefaultConfig.versionMajor * 10000 + DefaultConfig.versionMinor * 100 + DefaultConfig.versionPatch
with versions 1.0 and 1.1 and Bitrise works fine.

2. Use the same configuration with 1.2 and Bitrise fails or it sets a wrong versionCode.

**Comment by Roland-Bak** [comment]
Hello @Juan-GS 👋

Does this issue still happen? I checked your builds and the latest ones are working without issues 🙂

**Comment by Juan-GS** [comment]
Hello @Roland-Bak, 
Yes, it is still happening. Yo see the latest ones working without issues due to I am using v 1.1. The issue happens in v1.2.
