### ISSUE TITLE
Step fails without throwing any error message

### ISSUE THREAD

**Issue by pzmudzinski** [bitrise-steplib/steps-change-android-versioncode-and-versionname#5]
Those are my logs:
```+------------------------------------------------------------------------------+

| (5) change-android-versioncode-and-versionname@1.0.0                         |
+------------------------------------------------------------------------------+
| id: change-android-versioncode-and-versionname                               |
| version: 1.0.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2018-01-30T22:45:23Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Configs:
- BuildGradlePth: build.gradle
- NewVersionName: 
- NewVersionCode: 51
- VersionCodeOffset: 
Updating versionName and versionCode in: build.gradle
0 versionCode updated
0 versionName updated
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | change-android-versioncode-and-versionname@1.0.0              | 3.25 sec |
+---+---------------------------------------------------------------+----------+
```

As you can see I've passed new version code (`$BITRISE_BUILD_NUMBER`), it was correctly picked up but step didn't change anything in `build.gradle`.

**Comment by viktorbenei** [comment]
Hi @pzmudzinski ,

Thanks for reporting!

Can you please share your `build.gradle` file? For some reason the step could not find the version name and version code in the `build.gradle` file. For debugging we'd need the `build.gradle` file.

**Comment by pzmudzinski** [comment]
This is it 
```
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'kotlin-kapt'

apply plugin: 'io.fabric'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "***********"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "***********"
        vectorDrawables {
            useSupportLibrary true
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            buildConfigField "String", "SERVER_URL", "***********"
        }
        debug {
            buildConfigField "String", "SERVER_URL", "***********"
        }
    }
}

dependencies {
  // bla bla bla 
}

apply plugin: 'com.google.gms.google-services'
```
Looks pretty standard, right?

**Comment by viktorbenei** [comment]
Thanks, we'll check it ASAP why the step can't find the version infos!

**Comment by viktorbenei** [comment]
We tried to reproduce this issue but so far we could not.

Can you please share the build's bitrise.io URL?

**Comment by pzmudzinski** [comment]
I think I know what's wrong. Step is using `GRADLE_BUILD_FILE_PATH` by default which points to project-wise `build.gradle` (with repositories definitions etc.) but there's no app-specific things there (like versionCode).   
It's explained here better:
https://stackoverflow.com/questions/23241681/why-are-there-two-build-gradle-files-in-an-android-studio-project
```
<PROJECT_ROOT>\app\build.gradle is specific for app module.

<PROJECT_ROOT>\build.gradle is a "Top-level build file" where you can add configuration options common to all sub-projects/modules.
```

I've changed gradle file path to `app/build.gradle` and it worked out. 
I think step should be modified to either have `app/build.gradle` by default or detect that someone is trying to use top-level build file and put a warning that probably he had `app/build.gradle` in mind.

**Comment by viktorbenei** [comment]
Got it, thanks for the details @pzmudzinski ! I'm glad to hear you managed to solve this - I'll bring this up for a discussion with the team! :)

**Comment by mspmax** [comment]
hi @viktorbenei, just to clarify something. Where do you put this step? I use it before gradle runner

**Comment by viktorbenei** [comment]
@mspmax you should add it right before you'd create the APK, usually right before the **Gradle Runner** step.
